version: '3.8'

services:
  # PostgreSQL Database (if you want to run locally, otherwise use external)
  postgresql:
    image: postgres:17.4-alpine
    hostname: postgresql
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ:-UTC}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT:-127.0.0.1:5432}:5432"
    networks:
      mail-network:
        aliases:
          - postgresql

  # Redis for caching and session management
  redis:
    image: redis:7.4.2-alpine
    hostname: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - "${REDIS_PORT:-127.0.0.1:26379}:6379"
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - ./data/redis:/data
    networks:
      mail-network:
        aliases:
          - redis

  # Rspamd for spam filtering
  rspamd:
    image: rspamd/rspamd:3.7
    hostname: rspamd
    depends_on:
      - redis
    environment:
      - TZ=${TZ:-UTC}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./config/rspamd/local.d:/etc/rspamd/local.d
      - ./config/rspamd/rspamd.conf:/etc/rspamd/rspamd.conf
      - ./data/rspamd:/var/lib/rspamd
      - ./logs/rspamd:/var/log/rspamd
    restart: always
    networks:
      mail-network:
        aliases:
          - rspamd

  # Dovecot for IMAP/POP3
  dovecot:
    build:
      context: ./docker/dovecot
      dockerfile: Dockerfile
    hostname: dovecot
    depends_on:
      - postgresql
      - redis
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ./config/dovecot/conf.d:/etc/dovecot/conf.d
      - ./config/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf
      - ./logs/dovecot:/var/log/mail
      - ./ssl:/etc/ssl/mail
      - ./data/vmail:/var/vmail
      - ./data/rspamd:/var/lib/rspamd
    environment:
      - DB_HOST=${DB_HOST:-postgresql}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ:-UTC}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${IMAP_PORT:-143}:143"
      - "${IMAPS_PORT:-993}:993"
      - "${POP_PORT:-110}:110"
      - "${POPS_PORT:-995}:995"
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    networks:
      mail-network:
        aliases:
          - dovecot

  # Postfix for SMTP
  postfix:
    build:
      context: ./docker/postfix
      dockerfile: Dockerfile
    hostname: postfix
    depends_on:
      - dovecot
      - rspamd
      - postgresql
    volumes:
      - ./config/postfix/main.cf:/etc/postfix/main.cf
      - ./config/postfix/master.cf:/etc/postfix/master.cf
      - ./config/postfix/sql:/etc/postfix/sql
      - ./logs/postfix:/var/log/mail
      - ./ssl:/etc/ssl/mail
      - ./data/postfix:/var/spool/postfix
      - ./data/rspamd:/var/lib/rspamd
    environment:
      - TZ=${TZ:-UTC}
      - DB_HOST=${DB_HOST:-postgresql}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MAIL_HOSTNAME=${MAIL_HOSTNAME}
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "${SMTP_PORT:-25}:25"
      - "${SMTPS_PORT:-465}:465"
      - "${SUBMISSION_PORT:-587}:587"
    restart: always
    networks:
      mail-network:
        aliases:
          - postfix

  # RoundCube Webmail
  webmail:
    image: roundcube/roundcubemail:1.6.10-fpm-alpine
    hostname: roundcube
    depends_on:
      - dovecot
      - postfix
      - postgresql
    volumes:
      - ./config/webmail:/var/roundcube/config
      - ./config/php:/usr/local/etc
      - ./data/webmail:/var/www/html
    environment:
      - TZ=${TZ:-UTC}
      - ROUNDCUBEMAIL_DB_TYPE=pgsql
      - ROUNDCUBEMAIL_DB_HOST=${DB_HOST:-postgresql}
      - ROUNDCUBEMAIL_DB_NAME=${DB_NAME}
      - ROUNDCUBEMAIL_DB_USER=${DB_USER}
      - ROUNDCUBEMAIL_DB_PASSWORD=${DB_PASSWORD}
      - ROUNDCUBEMAIL_DEFAULT_HOST=dovecot
      - ROUNDCUBEMAIL_DEFAULT_PORT=${IMAP_PORT:-143}
      - ROUNDCUBEMAIL_SMTP_SERVER=postfix
      - ROUNDCUBEMAIL_SMTP_PORT=${SMTP_PORT:-25}
      - ROUNDCUBEMAIL_REQUEST_PATH=/webmail
    restart: always
    networks:
      mail-network:
        aliases:
          - webmail

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    hostname: nginx
    depends_on:
      - webmail
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/ssl/mail
      - ./logs/nginx:/var/log/nginx
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    restart: always
    networks:
      mail-network:
        aliases:
          - nginx

networks:
  mail-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
